### PR TITLE
relead fixed

### PR DESCRIPTION
**Pull request by ScureX**
your're'E are stumnpid

### CODE REVIEW

**Comment by BigSpice** [comment]
i know :(

**Comment by ConnorDoesDev** [comment]
what

**Review by ConnorDoesDev — APPROVED** [review]
i approve the stupidity fix. :trollface:

**Comment by ScureX** [comment]
ver y iumprotant fix!!! must do sevperate release immediatalyx :trollface:

**Comment by BigSpice** [comment]
damn
was hoping i could stall

**Comment by ConnorDoesDev** [comment]
lol

**Pull request merged**
