### PR TITLE
fix about text

### PR DESCRIPTION
**Pull request by themoonisacheese**
noticed a typo in "northstar" and took the oportunity to fix various grammatical or capitalization issues

### CODE REVIEW

**Comment by BigSpice** [comment]
gonna read this through rq

**Comment by BigSpice** [comment]
sheesh
i cant spell for Shit
Ty @themoonisacheese

**Comment by ConnorDoesDev** [comment]
one sec

**Review by BigSpice — APPROVED** [review]
Good from me

**Review by ConnorDoesDev — APPROVED** [review]
looks good to me

**Pull request merged**
